### ISSUE TITLE
How do I write a todo comment and have it show up in the sidebar?

### ISSUE THREAD

**Issue by akoskinen** [Yizen/Coda-TODO-plugin#2]
Hey,

Dumb question here.. but if I write  to the html file, shouldn't that comment show up in the sidebar?

What am I missing?

Do I have to close and reopen something for a parse scan to occur first or what? That'd be kinda tedious though :)

ak

**Comment by yizen** [comment]
Hi akoskinen,

Currently, only  will be picked up by the parser (notice the double slash before the TODO  : //TODO)

Matching  will need some work on the regexps.

Parsing is done at open time and at focus (clicking on the thumbnail in the upper tab bar).

I haven't implemented yet an autorefresh for the current file: adding a scheduled task (every 10 minutes) that would scan the text content might slow down your editing on large files, or slow computers if Coda is not multitasking the plugins-generated task... This is issue #1.

**Comment by firmmedia** [comment]
@akoskinen 
I was experiencing the same issue.  Another thing to note on this is that if you would like the todo item to not show the closing comment code then make sure that the comment is closed on another line. 

**HTML Example:**

```
  <!-- implemented with an html comment, 
    //OPTIMIZE: Sample optimize comment
    //TODO: Sample TODO comment
  -->
```

**The Todo items can also be added in a php comment like so:**

```
<?php //TODO: Sample of a TODO in a php comment
echo 'This also works in php yay!';?> 
```

Hope that this helps some.

@Yizen Thank you for the great plugin.
