### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by showcasefloyd** [Yizen/Coda-TODO-plugin#5]
I have a TODO.txt file in my project, but the window is empty. Any idea how to troubleshoot this thing?

**Comment by yizen** [comment]
Actually, the plugin just scans the current file, scans the document for comments like //TODO: and  //FIXME: (like in this example : http://www.panozzaj.com/blog/2010/01/15/todo-fixme-hack-and-xxx/) and populate the panel based on the scan results.

So it will currently ignore your TODO.txt file, but that might be a good evolution idea! Hope you'll find the plugin useful anyway.

**Comment by showcasefloyd** [comment]
Oh I see. I miss understood. I thought it was looking for any file called TODO.txt or FIXME.txt or possible NOTES.md. Gotcha. Thanks for the help
